/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.table.DefaultTableModel;
import model.car;
import model.carFleet;

/**
 *
 * @author krish
 */
public class AllAvailJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AllAvailJPanel
     */
    
    carFleet fleet;
    
    public AllAvailJPanel(carFleet fleet) {
        initComponents();
        
        this.fleet = fleet;
        
        String availstatus = "Yes";
        
        populateAllAvailTable(availstatus);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAllAvail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAllAvail = new javax.swing.JTable();

        lblAllAvail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAllAvail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAllAvail.setText("All available cars");

        tblAllAvail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Serial No.", "Model No.", "City", "Availability", "Last update"
            }
        ));
        jScrollPane1.setViewportView(tblAllAvail);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAllAvail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAllAvail)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAllAvail;
    private javax.swing.JTable tblAllAvail;
    // End of variables declaration//GEN-END:variables

    private void populateAllAvailTable(String availstatus) {
        DefaultTableModel allAvailModel = (DefaultTableModel) tblAllAvail.getModel(); // typecasting into DefaultTableModel class type
        allAvailModel.setRowCount(0);
        
        for(car carAdded: fleet.getFleet()){
            if( carAdded.getAvailability().equals(availstatus)){
                Object[] row = new Object[5]; // one for each column
                row[0] = carAdded.getSerialNo(); // first column becomes the actual object
                row[1] = carAdded.getModelNo();
                row[2] = carAdded.getCity();
                row[3] = carAdded.getAvailability();
                row[4] = carAdded.getLastUpdate();
            
            allAvailModel.addRow(row);
            }
        }
    }
}
