/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.table.DefaultTableModel;
import model.car;
import model.carFleet;

/**
 *
 * @author krish
 */
public class InvalidCertiJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InvalidCertiJPanel
     */
    carFleet fleet;
    
    public InvalidCertiJPanel(carFleet fleet) {
        initComponents();
        
        this.fleet = fleet;
        
        String status = "Invalid";
        populateLastUpdate(status);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCertiStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCertiStatus = new javax.swing.JTable();

        lblCertiStatus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCertiStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCertiStatus.setText("Search cars with invalid maintenance certificate");

        tblCertiStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Serial No.", "Model No.", "City", "Maintenance Certificate Status"
            }
        ));
        jScrollPane1.setViewportView(tblCertiStatus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCertiStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCertiStatus)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCertiStatus;
    private javax.swing.JTable tblCertiStatus;
    // End of variables declaration//GEN-END:variables

    private void populateLastUpdate(String status) {
        DefaultTableModel statusModel = (DefaultTableModel) tblCertiStatus.getModel(); // typecasting into DefaultTableModel class type
        statusModel.setRowCount(0);
        
        for(car carAdded: fleet.getFleet()){
            if( carAdded.getMaintenanceCertiStatus().equals(status)){
                Object[] row = new Object[4]; // one for each column
                row[0] = carAdded.getSerialNo(); // first column becomes the actual object
                row[1] = carAdded.getModelNo();
                row[2] = carAdded.getCity();
                row[3] = carAdded.getMaintenanceCertiStatus();
                statusModel.addRow(row);
            }
        }
    }
}