/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.table.DefaultTableModel;
import model.car;
import model.carFleet;

/**
 *
 * @author krish
 */
public class LastUpdateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LastUpdateJPanel
     */
    
    carFleet fleet;
    public LastUpdateJPanel(carFleet fleet) {
        initComponents();
        this.fleet = fleet;
        
        populateLastUpdateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLastUpdate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLastUpdate = new javax.swing.JTable();

        lblLastUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLastUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLastUpdate.setText("Manufacturer List");

        tblLastUpdate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Serial No.", "Last Update"
            }
        ));
        jScrollPane1.setViewportView(tblLastUpdate);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLastUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLastUpdate)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLastUpdate;
    private javax.swing.JTable tblLastUpdate;
    // End of variables declaration//GEN-END:variables

    private void populateLastUpdateTable() {
        DefaultTableModel updateModel = (DefaultTableModel) tblLastUpdate.getModel(); // typecasting into DefaultTableModel class type
        updateModel.setRowCount(0);
        
        for(car carAdded: fleet.getFleet()){
            Object[] row = new Object[2]; // one for each column
            row[0] = carAdded.getSerialNo(); // first column becomes the actual object
            row[1] = carAdded.getLastUpdate();
            
            updateModel.addRow(row);
        }
    }
}
