/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.carFleet;

/**
 *
 * @author krish
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    carFleet fleet; // instance for carFleet class
    
    
    public MainJFrame() {
        initComponents();
        // initializing
        fleet = new carFleet(); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        btnViewCars = new javax.swing.JButton();
        btnManuf = new javax.swing.JButton();
        btnManufYear = new javax.swing.JButton();
        btnSeats = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnFindModel = new javax.swing.JButton();
        btnLastUpdate = new javax.swing.JButton();
        btnValidCerti = new javax.swing.JButton();
        btnSearchManuf = new javax.swing.JButton();
        btnCity = new javax.swing.JButton();
        btnAllAvail = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegister.setText("Register a car");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnViewCars.setText("View all cars");
        btnViewCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCarsActionPerformed(evt);
            }
        });

        btnManuf.setText("Manufacturer list");
        btnManuf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManufActionPerformed(evt);
            }
        });

        btnManufYear.setText("Car manufacture year");
        btnManufYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManufYearActionPerformed(evt);
            }
        });

        btnSeats.setText("Find car based on number of seats");
        btnSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeatsActionPerformed(evt);
            }
        });

        btnFind.setText("Find a car with serial number");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnFindModel.setText("Car model search");
        btnFindModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindModelActionPerformed(evt);
            }
        });

        btnLastUpdate.setText("Last update details");
        btnLastUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastUpdateActionPerformed(evt);
            }
        });

        btnValidCerti.setText("Cars with invalid maintenance certificate");
        btnValidCerti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidCertiActionPerformed(evt);
            }
        });

        btnSearchManuf.setText("Find car from particular manufacturer");
        btnSearchManuf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchManufActionPerformed(evt);
            }
        });

        btnCity.setText("Find car with city name");
        btnCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCityActionPerformed(evt);
            }
        });

        btnAllAvail.setText("Find all available cars");
        btnAllAvail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllAvailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnValidCerti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLastUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewCars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManuf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManufYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSeats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFindModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSearchManuf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAllAvail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnFind, btnFindModel, btnLastUpdate, btnManuf, btnManufYear, btnRegister, btnSearchManuf, btnSeats, btnValidCerti, btnViewCars});

        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewCars)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManuf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManufYear, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFindModel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchManuf, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnLastUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnValidCerti, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCity)
                .addGap(18, 18, 18)
                .addComponent(btnAllAvail)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnFind, btnFindModel, btnLastUpdate, btnManuf, btnManufYear, btnRegister, btnSearchManuf, btnSeats, btnValidCerti, btnViewCars});

        splitPane.setLeftComponent(controlPanel);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to UberFleet!");

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addContainerGap())
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addContainerGap(375, Short.MAX_VALUE))
        );

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        RegisterJPanel registerPanel = new RegisterJPanel(fleet);
        splitPane.setRightComponent(registerPanel);
        
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnViewCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCarsActionPerformed
        // TODO add your handling code here:
        ViewJPanel viewPanel = new ViewJPanel(fleet);
        splitPane.setRightComponent(viewPanel);
        
    }//GEN-LAST:event_btnViewCarsActionPerformed

    private void btnManufYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManufYearActionPerformed
        // TODO add your handling code here:
        ManufYearJPanel manufYrPanel = new ManufYearJPanel(fleet);
        splitPane.setRightComponent(manufYrPanel);
        
    }//GEN-LAST:event_btnManufYearActionPerformed

    private void btnSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeatsActionPerformed
        // TODO add your handling code here:
        SeatJPanel seatPanel = new SeatJPanel(fleet);
        splitPane.setRightComponent(seatPanel);
    }//GEN-LAST:event_btnSeatsActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        SearchSerialNoJPanel searchSerialNoPanel = new SearchSerialNoJPanel(fleet);
        splitPane.setRightComponent(searchSerialNoPanel);
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnFindModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindModelActionPerformed
        // TODO add your handling code here:
        SearchModelJPanel searchModelPanel = new SearchModelJPanel(fleet);
        splitPane.setRightComponent(searchModelPanel);
    }//GEN-LAST:event_btnFindModelActionPerformed

    private void btnLastUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastUpdateActionPerformed
        // TODO add your handling code here:
        LastUpdateJPanel updatePanel = new LastUpdateJPanel(fleet);
        splitPane.setRightComponent(updatePanel);
    }//GEN-LAST:event_btnLastUpdateActionPerformed

    private void btnValidCertiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidCertiActionPerformed
        // TODO add your handling code here:
        InvalidCertiJPanel statusPanel = new InvalidCertiJPanel(fleet);
        splitPane.setRightComponent(statusPanel);
    }//GEN-LAST:event_btnValidCertiActionPerformed

    private void btnManufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManufActionPerformed
        // TODO add your handling code here:
        ManufJPanel manufPanel = new ManufJPanel(fleet);
        splitPane.setRightComponent(manufPanel);
    }//GEN-LAST:event_btnManufActionPerformed

    private void btnSearchManufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchManufActionPerformed
        // TODO add your handling code here:
        SearchManufJPanel searchManufPanel = new SearchManufJPanel(fleet);
        splitPane.setRightComponent(searchManufPanel);
    }//GEN-LAST:event_btnSearchManufActionPerformed

    private void btnAllAvailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllAvailActionPerformed
        // TODO add your handling code here:
        AllAvailJPanel allAvailPanel = new AllAvailJPanel(fleet);
        splitPane.setRightComponent(allAvailPanel);
    }//GEN-LAST:event_btnAllAvailActionPerformed

    private void btnCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCityActionPerformed
        // TODO add your handling code here:
        SearchCityJPanel searchCityPanel = new SearchCityJPanel(fleet);
        splitPane.setRightComponent(searchCityPanel);
    }//GEN-LAST:event_btnCityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllAvail;
    private javax.swing.JButton btnCity;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFindModel;
    private javax.swing.JButton btnLastUpdate;
    private javax.swing.JButton btnManuf;
    private javax.swing.JButton btnManufYear;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSearchManuf;
    private javax.swing.JButton btnSeats;
    private javax.swing.JButton btnValidCerti;
    private javax.swing.JButton btnViewCars;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
