/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.car;
import model.carFleet;

/**
 *
 * @author krish
 */
public class ManufYearJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManufYearJPanel
     */
    carFleet fleet; 
    
    public ManufYearJPanel(carFleet fleet) {
        initComponents();
        
        this.fleet = fleet;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManufYear = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManufYear = new javax.swing.JTable();
        lblSearchYear = new javax.swing.JLabel();
        txtSearchYear = new javax.swing.JTextField();
        btnSearchYear = new javax.swing.JButton();

        lblManufYear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblManufYear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManufYear.setText("Car manufacture year");

        tblManufYear.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Serial No.", "Model No.", "Manufacturer", "Year of Make"
            }
        ));
        jScrollPane1.setViewportView(tblManufYear);

        lblSearchYear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSearchYear.setText("Enter year:");

        txtSearchYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchYearActionPerformed(evt);
            }
        });

        btnSearchYear.setText("Search");
        btnSearchYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchYearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblManufYear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSearchYear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearchYear, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(txtSearchYear))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSearchYear, txtSearchYear});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblManufYear)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchYear)
                    .addComponent(txtSearchYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchYear)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblSearchYear, txtSearchYear});

    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchYearActionPerformed
        // TODO add your handling code here:
        int searchYear = 0;
        searchYear = Integer.parseInt(txtSearchYear.getText());
        
        populateManufYearTable(searchYear);
        
    }//GEN-LAST:event_btnSearchYearActionPerformed

    private void txtSearchYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchYearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchYear;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblManufYear;
    private javax.swing.JLabel lblSearchYear;
    private javax.swing.JTable tblManufYear;
    private javax.swing.JTextField txtSearchYear;
    // End of variables declaration//GEN-END:variables

    private void populateManufYearTable(int searchYear) {
        DefaultTableModel manufYearModel = (DefaultTableModel) tblManufYear.getModel(); // typecasting into DefaultTableModel class type
        manufYearModel.setRowCount(0);
        
        for(car carAdded: fleet.getFleet()){
            Object[] row = new Object[4]; // one for each column
            if( carAdded.getYearOfMake() == searchYear){
                row[0] = carAdded.getSerialNo();
                row[1] = carAdded.getModelNo();
                row[2] = carAdded.getManufacturer();
                row[3] = carAdded.getYearOfMake();
                manufYearModel.addRow(row);
            } // first column becomes the actual object
        }      
    }
}
