/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.table.DefaultTableModel;
import model.car;
import model.carFleet;

/**
 *
 * @author krish
 */
public class ManufJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManufJPanel
     */
    
    carFleet fleet;
    
    public ManufJPanel(carFleet fleet) {
        initComponents();
        
        this.fleet = fleet;
        
        populateManufTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManuf = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManuf = new javax.swing.JTable();

        lblManuf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblManuf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManuf.setText("Manufacturer List");

        tblManuf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Manufacturer", "Model number"
            }
        ));
        jScrollPane1.setViewportView(tblManuf);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblManuf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblManuf)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblManuf;
    private javax.swing.JTable tblManuf;
    // End of variables declaration//GEN-END:variables

    private void populateManufTable() {
        
        DefaultTableModel manufModel = (DefaultTableModel) tblManuf.getModel(); // typecasting into DefaultTableModel class type
        manufModel.setRowCount(0);
        
        for(car carAdded: fleet.getFleet()){
            Object[] row = new Object[2]; // one for each column
            row[0] = carAdded.getManufacturer(); // first column becomes the actual object
            row[1] = carAdded.getModelNo();
            
            manufModel.addRow(row);
        }
        
        }
}
