/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import model.car;
import model.carFleet;

/**
 *
 * @author krish
 */
public class RegisterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterJPanel
     */
    carFleet fleet;
    
    public RegisterJPanel(carFleet fleet) {
        initComponents();
        
        this.fleet = fleet;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSerialNo = new javax.swing.JLabel();
        lblModelNo = new javax.swing.JLabel();
        lblManufacturer = new javax.swing.JLabel();
        lblYearOfMake = new javax.swing.JLabel();
        lblNoOfSeats = new javax.swing.JLabel();
        lblCertificateStatus = new javax.swing.JLabel();
        lblAvailability = new javax.swing.JLabel();
        txtSerialNo = new javax.swing.JTextField();
        txtModelNo = new javax.swing.JTextField();
        txtManufacturer = new javax.swing.JTextField();
        txtYearOfMake = new javax.swing.JTextField();
        txtNoOfSeats = new javax.swing.JTextField();
        checkboxYes = new javax.swing.JCheckBox();
        btnSave = new javax.swing.JButton();
        checkboxValid = new javax.swing.JCheckBox();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("UberFleet Registration");

        lblSerialNo.setText("Serial Number:");

        lblModelNo.setText("Model Number:");

        lblManufacturer.setText("Manufacturer:");

        lblYearOfMake.setText("Year of Make:");

        lblNoOfSeats.setText("No. of Seats:");

        lblCertificateStatus.setText("Maintenance Certificate Valid?:");

        lblAvailability.setText("Is the car available?");

        checkboxYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxYesActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        checkboxValid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxValidActionPerformed(evt);
            }
        });

        lblCity.setText("City:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCertificateStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(lblAvailability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkboxYes)
                            .addComponent(checkboxValid)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSerialNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblModelNo, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(lblManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNoOfSeats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblYearOfMake, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSerialNo)
                            .addComponent(txtModelNo)
                            .addComponent(txtManufacturer)
                            .addComponent(txtYearOfMake)
                            .addComponent(txtNoOfSeats, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(txtCity, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCity, txtNoOfSeats});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerialNo)
                    .addComponent(txtSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufacturer)
                    .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYearOfMake)
                    .addComponent(txtYearOfMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoOfSeats)
                    .addComponent(txtNoOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCertificateStatus)
                    .addComponent(checkboxValid))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailability)
                    .addComponent(checkboxYes))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCity, txtNoOfSeats});

    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String serialNo = txtSerialNo.getText();
        String modelNo = txtModelNo.getText();
        String availability = "";
        String manufacturer = txtManufacturer.getText();
        int yearOfMake = Integer.parseInt(txtYearOfMake.getText());
        int noOfSeats = Integer.parseInt(txtNoOfSeats.getText());
        String city = txtCity.getText();
        String lastUpdate = new SimpleDateFormat("h:mm a").format(new Date());
        // String lastUpdate = txtLastUpdate.getText();
        String maintenanceCertiStatus = "";
        
        
        if(checkboxYes.isSelected()){
            availability = "Yes";
        }
        else {
            availability = "No";
            
        }        
        if(checkboxValid.isSelected()){
            maintenanceCertiStatus = "Valid";
        }
        else {
            maintenanceCertiStatus = "Invalid";
            
        }

        
        if( !serialNo.isEmpty() && !modelNo.isEmpty() && !manufacturer.isEmpty() && !city.isEmpty() && !txtYearOfMake.getText().isEmpty() && !txtNoOfSeats.getText().isEmpty() ){  

            car carAdded = fleet.registerNewCar();
            
            carAdded.setSerialNo(serialNo);
            carAdded.setModelNo(modelNo);
            carAdded.setManufacturer(manufacturer);
            carAdded.setYearOfMake(yearOfMake);
            carAdded.setNoOfSeats(noOfSeats);
            carAdded.setCity(city);
            carAdded.setLastUpdate(lastUpdate);
            carAdded.setMaintenanceCertiStatus(maintenanceCertiStatus);
            carAdded.setAvailability(availability);
            JOptionPane.showMessageDialog(this, "Car registration successful!");
        }
        if( serialNo.isEmpty() || modelNo.isEmpty() || manufacturer.isEmpty() || city.isEmpty() ){
            JOptionPane.showMessageDialog(this, "Fields cannot be empty! Try again!");
        }
        txtSerialNo.setText("");
        txtModelNo.setText("");
        txtManufacturer.setText("");
        txtYearOfMake.setText("");
        txtNoOfSeats.setText("");
        // txtLastUpdate.setText("");
        txtCity.setText("");
       
        checkboxYes.setSelected(false);
        checkboxValid.setSelected(false);
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void checkboxYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxYesActionPerformed
        // TODO add your handling code here:  
                 
    }//GEN-LAST:event_checkboxYesActionPerformed

    private void checkboxValidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxValidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxValidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox checkboxValid;
    private javax.swing.JCheckBox checkboxYes;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblCertificateStatus;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblModelNo;
    private javax.swing.JLabel lblNoOfSeats;
    private javax.swing.JLabel lblSerialNo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblYearOfMake;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtManufacturer;
    private javax.swing.JTextField txtModelNo;
    private javax.swing.JTextField txtNoOfSeats;
    private javax.swing.JTextField txtSerialNo;
    private javax.swing.JTextField txtYearOfMake;
    // End of variables declaration//GEN-END:variables
}
