/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.car;
import model.carFleet;

/**
 *
 * @author krish
 */
public class SearchManufJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchManufJPanel
     */
    
    carFleet fleet;
    public SearchManufJPanel(carFleet fleet) {
        initComponents();
        
        this.fleet = fleet;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearchManuf = new javax.swing.JTable();
        lblSearchNo = new javax.swing.JLabel();
        txtSearchManuf = new javax.swing.JTextField();
        btnSearchManuf = new javax.swing.JButton();
        lblSearchManuf = new javax.swing.JLabel();

        tblSearchManuf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Serial No.", "Model No.", "Number of Seats", "Manufacturer"
            }
        ));
        jScrollPane1.setViewportView(tblSearchManuf);

        lblSearchNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSearchNo.setText("Enter manufacturer:");

        btnSearchManuf.setText("Search");
        btnSearchManuf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchManufActionPerformed(evt);
            }
        });

        lblSearchManuf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSearchManuf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearchManuf.setText("Search car with manufacturer name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSearchManuf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSearchNo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSearchManuf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSearchManuf, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSearchManuf)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchNo)
                    .addComponent(txtSearchManuf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSearchManuf)
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchManufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchManufActionPerformed
        // TODO add your handling code here:
        String searchManuf = "";
        searchManuf = txtSearchManuf.getText();

        populateSearchManufTable(searchManuf);
    }//GEN-LAST:event_btnSearchManufActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchManuf;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSearchManuf;
    private javax.swing.JLabel lblSearchNo;
    private javax.swing.JTable tblSearchManuf;
    private javax.swing.JTextField txtSearchManuf;
    // End of variables declaration//GEN-END:variables

    private void populateSearchManufTable(String searchManuf) {
        DefaultTableModel searchManufModel = (DefaultTableModel) tblSearchManuf.getModel(); // typecasting into DefaultTableModel class type
        searchManufModel.setRowCount(0);
        
        for(car carAdded: fleet.getFleet()){
            Object[] row = new Object[4]; // one for each column
            if( carAdded.getManufacturer().equals(searchManuf)){
                row[0] = carAdded.getSerialNo();
                row[1] = carAdded.getModelNo();
                row[2] = carAdded.getNoOfSeats();
                row[3] = carAdded.getManufacturer();
                searchManufModel.addRow(row);
            } // first column becomes the actual object
        }
    }
}