/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.car;
import model.carFleet;

/**
 *
 * @author krish
 */
public class SearchModelJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchModelJPanel
     */
    
    carFleet fleet; 
    public SearchModelJPanel(carFleet fleet) {
        initComponents();
        this.fleet = fleet;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearchModel = new javax.swing.JTable();
        lblSearchNo = new javax.swing.JLabel();
        txtSearchModel = new javax.swing.JTextField();
        btnSearchModel = new javax.swing.JButton();
        lblSearchModel = new javax.swing.JLabel();

        tblSearchModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Serial No.", "Model No.", "Manufacturer", "No. of seats"
            }
        ));
        jScrollPane1.setViewportView(tblSearchModel);

        lblSearchNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSearchNo.setText("Enter model no:");

        btnSearchModel.setText("Search");
        btnSearchModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchModelActionPerformed(evt);
            }
        });

        lblSearchModel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSearchModel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearchModel.setText("Search car with model number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSearchModel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSearchNo)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSearchModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSearchModel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSearchModel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchNo)
                    .addComponent(txtSearchModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSearchModel)
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchModelActionPerformed
        // TODO add your handling code here:
        String searchModelNo = "";
        searchModelNo = txtSearchModel.getText();

        populateSearchModelTable(searchModelNo);
    }//GEN-LAST:event_btnSearchModelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchModel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSearchModel;
    private javax.swing.JLabel lblSearchNo;
    private javax.swing.JTable tblSearchModel;
    private javax.swing.JTextField txtSearchModel;
    // End of variables declaration//GEN-END:variables

    private void populateSearchModelTable(String searchModelNo) {
        DefaultTableModel searchModelModel = (DefaultTableModel) tblSearchModel.getModel(); // typecasting into DefaultTableModel class type
        searchModelModel.setRowCount(0);
        
        for(car carAdded: fleet.getFleet()){
            Object[] row = new Object[4]; // one for each column
            if( carAdded.getModelNo().equals(searchModelNo)){
                row[0] = carAdded.getSerialNo();
                row[1] = carAdded.getModelNo();
                row[2] = carAdded.getManufacturer();
                row[3] = carAdded.getNoOfSeats();
                searchModelModel.addRow(row);
            } // first column becomes the actual object
    
        }
    }
}
