/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.car;
import model.carFleet;

/**
 *
 * @author krish
 */
public class SearchSerialNoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchSerialNoJPanel
     */
    carFleet fleet;
    
    public SearchSerialNoJPanel(carFleet fleet) {
        initComponents();
        
        this.fleet = fleet;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSearchSerialNo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearchSerialNo = new javax.swing.JTable();
        lblSearchNo = new javax.swing.JLabel();
        txtSearchNo = new javax.swing.JTextField();
        btnSearchNo = new javax.swing.JButton();

        lblSearchSerialNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSearchSerialNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearchSerialNo.setText("Search car with serial number");

        tblSearchSerialNo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Serial no.", "Model no.", "Availability", "Manufacturer", "Year of make", "No. of seats", "Last update", "Maintenance certificate status", "City"
            }
        ));
        jScrollPane1.setViewportView(tblSearchSerialNo);

        lblSearchNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSearchNo.setText("Enter serial no.:");

        btnSearchNo.setText("Search");
        btnSearchNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSearchSerialNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSearchNo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSearchNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSearchNo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSearchSerialNo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchNo)
                    .addComponent(txtSearchNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSearchNo)
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchNoActionPerformed
        // TODO add your handling code here:
        String searchSerialNo = "";
        searchSerialNo = txtSearchNo.getText();

        populateSearchSerialTable(searchSerialNo);

    }//GEN-LAST:event_btnSearchNoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchNo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSearchNo;
    private javax.swing.JLabel lblSearchSerialNo;
    private javax.swing.JTable tblSearchSerialNo;
    private javax.swing.JTextField txtSearchNo;
    // End of variables declaration//GEN-END:variables

    private void populateSearchSerialTable(String searchSerialNo) {
        DefaultTableModel searchSerialModel = (DefaultTableModel) tblSearchSerialNo.getModel(); // typecasting into DefaultTableModel class type
        searchSerialModel.setRowCount(0);
        
        for(car carAdded: fleet.getFleet()){
            Object[] row = new Object[9]; // one for each column
            if( carAdded.getSerialNo().equals(searchSerialNo)){
                row[0] = carAdded.getSerialNo();
                row[1] = carAdded.getModelNo();
                row[2] = carAdded.getAvailability();
                row[3] = carAdded.getManufacturer();
                row[4] = carAdded.getYearOfMake();
                row[5] = carAdded.getNoOfSeats();
                row[6] = carAdded.getLastUpdate();
                row[7] = carAdded.getMaintenanceCertiStatus();
                row[8] = carAdded.getCity();
                
                searchSerialModel.addRow(row);
            } // first column becomes the actual object
        }
    }
}
