/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.car;
import model.carFleet;

/**
 *
 * @author krish
 */
public class SeatJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SeatJPanel
     */
    
    carFleet fleet;
    
    public SeatJPanel(carFleet fleet) {
        initComponents();
        this.fleet = fleet;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSeatNo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSeats = new javax.swing.JTable();
        lblMin = new javax.swing.JLabel();
        txtMin = new javax.swing.JTextField();
        btnSearchYear = new javax.swing.JButton();
        lblMax = new javax.swing.JLabel();
        txtMax = new javax.swing.JTextField();

        lblSeatNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSeatNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeatNo.setText("Car capacity");

        tblSeats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Serial No.", "Model No.", "Manufacturer", "Seats"
            }
        ));
        jScrollPane1.setViewportView(tblSeats);

        lblMin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMin.setText("Minimum capacity:");

        btnSearchYear.setText("Search");
        btnSearchYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchYearActionPerformed(evt);
            }
        });

        lblMax.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMax.setText("Maximum capacity:");

        txtMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSeatNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSearchYear, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblMax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblMin, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMin)
                                    .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSeatNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMin)
                    .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMax)
                    .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchYear)
                .addContainerGap(123, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchYearActionPerformed
        // TODO add your handling code here:
        int seatMin = 0;
        seatMin = Integer.parseInt(txtMin.getText());
        int seatMax = 0;
        seatMax = Integer.parseInt(txtMax.getText());

        populateSearchSeatTable(seatMin, seatMax);

    }//GEN-LAST:event_btnSearchYearActionPerformed

    private void txtMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchYear;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMax;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblSeatNo;
    private javax.swing.JTable tblSeats;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtMin;
    // End of variables declaration//GEN-END:variables

    private void populateSearchSeatTable(int seatMin, int seatMax) {
        DefaultTableModel seatsModel = (DefaultTableModel) tblSeats.getModel(); // typecasting into DefaultTableModel class type
        seatsModel.setRowCount(0);
        
        for(car carAdded: fleet.getFleet()){
            Object[] row = new Object[4]; // one for each column
            if( carAdded.getNoOfSeats() >= seatMin && carAdded.getNoOfSeats() <= seatMax){
                row[0] = carAdded.getSerialNo();
                row[1] = carAdded.getModelNo();
                row[2] = carAdded.getManufacturer();
                row[3] = carAdded.getNoOfSeats();
                seatsModel.addRow(row);
            } // first column becomes the actual object
        }
    }
}
